version: '3.7'
services:
  postgres:
    container_name: postgres
    restart: always
    image: postgres
    build:
      context: ./postgres
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: postgraphile
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    networks:
      - private
    ports:
      - 5432:5432

  flyway:
    container_name: flyway
    image: flyway/flyway
    command: migrate
    restart: on-failure
    depends_on:
      - postgres
    volumes:
      - ./postgres/migrations/:/flyway/sql
      - ./postgres/config:/flyway/conf

  graphql:
    container_name: graphql
    restart: always
    image: graphile/postgraphile
    build:
      context: ./graphql
    environment:
      DATABASE_URL: postgres://postgres:password@postgres:5432/postgraphile
    depends_on:
      - postgres
      - flyway
    networks:
      - private
    ports:
      - 5433:5433
    command: [
      "--connection", "postgres://postgres:password@postgres:5432/postgraphile",
      "--schema", "pawk",
      "--port", "5433",
      "--append-plugins", "postgraphile-plugin-connection-filter"
    ]

  # webscraper:
  #   container_name: webscraper
  #   restart: always
  #   image: node
  #   build:
  #     context: ./webscraper
  #   depends_on:
  #     - graphql
  #   networks:
  #     - private

networks:
  private:

volumes:
  db: